# Generated by Django 4.2.5 on 2023-09-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticketapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="organization",
            field=models.CharField(max_length=50),
        ),
    ]
